- hosts: pteroall
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: no
  pre_tasks:
    - name: Install Python
      raw: 'type python3 >/dev/null 2>&1 || apt-get -y install python3-minimal'
      changed_when: false
    - name: Gather Facts
      setup:
  roles:
    - ntp
    - epel
    - firewalld

- hosts: pteropanel
  become: yes
  become_method: sudo
  strategy: free
  roles:
    - pteropanelupgrade

- hosts: pterodaemon
  become: yes
  become_method: sudo
  strategy: free
  roles:
    - pterodaemonupgrade