---
- name: CentOS | Install Panel Dependencies
  yum:
    state: "present"
    name:
      - "mod_php74"
      - "php74-common"
      - "php74-fpm"
      - "php74-cli"
      - "php74-json"
      - "php74-mysqlnd"
      - "php74-gd"
      - "php74-mbstring"
      - "php74-pdo"
      - "php74-bcmath"
      - "php74-xml"
      - "php74-opcache"
      - "php74-pecl-zip"
      - "nginx"
      - "redis"
      - "libselinux-python"
      - "policycoreutils-python"

- name: CentOS | Start the Redis Service
  service: name=redis state=started enabled=yes
...
