---
- name: Ubuntu | Add the PHP Repository
  apt_repository:
    repo: ppa:ondrej/php
  when: ansible_distribution|lower == 'ubuntu'

- name: Ubuntu | Add the Redis Repository
  apt_repository:
    repo: ppa:chris-lea/redis-server
  when: ansible_distribution|lower == 'ubuntu'

- name: Debian | Pre-req Packages
  apt:
    name:
      - "apt-transport-https"
    state: "present"

- name: Debian | Get the php GPG key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: "present"
  when: ansible_distribution|lower == 'debian'

- name: Debian | Add the PHP Repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_lsb.codename }} main
    state: "present"
  when: ansible_distribution|lower == 'debian'

- name: Debian/Ubuntu | Install Panel Dependencies
  apt:
    update_cache: "yes"
    state: "present"
    name:
      - "sudo"
      - "php8.1"
      - "php8.1-cli"
      - "php8.1-gd"
      - "php8.1-mysql"
      - "php8.1-common"
      - "php8.1-mbstring"
      - "php8.1-bcmath"
      - "php8.1-xml"
      - "php8.1-fpm"
      - "php8.1-curl"
      - "php8.1-zip"
      - "python3-mysqldb"
      - "nginx"
      - "curl"
      - "tar"
      - "unzip"
      - "git"
      - "redis-server"

- name: Debian/Ubuntu | Start the Redis Service
  service: name=redis-server state=started enabled=yes
...