---
- debug:
    msg: "Starting upgrade to {{ latest_ptdversion }}"
  when: do_upgrade is defined

- name: Stop the Wings Service
  service: name=wings enabled=yes state=stopped

- name: Download Daemon File
  get_url:
    url: "https://github.com/pterodactyl/wings/releases/download/v{{ latest_ptdversion }}/wings_linux_amd64"
    dest: "/usr/local/bin/wings"
    mode: "u+x"
    force: yes

...