---
- include: versioncheck.yml

- name: Create Daemon Folders
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - "/etc/pterodactyl"
    - "{{ ptd_dir }}/daemon-data"

- name: Download Daemon File
  get_url:
    url: "https://github.com/pterodactyl/wings/releases/download/v{{ latest_ptdversion }}/wings_linux_amd64"
    dest: "/usr/local/bin/wings"
    mode: "u+x"
    force: yes

- name: Create the Daemon Service
  template:
    src: templates/wings.j2
    dest: /etc/systemd/system/wings.service

- name: Enable the Wings Service
  service: name=wings enabled=yes

- name: Add Certbot cron.daily File
  template:
    src: templates/certbot.j2
    dest: /etc/cron.daily/certbot-daemon
    mode: '0755'
    force: no
...