---
- name: Check for latest version
  uri: url="https://api.github.com/repos/pterodactyl/wings/releases/latest" return_content="yes"
  register: ptdversion

- set_fact:
    latest_ptdversion: "{{ ptdversion.json.tag_name | regex_search('([0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})') }}"
...